# Generated by Django 4.1.2 on 2022-10-20 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
