# Generated by Django 4.1.1 on 2022-10-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
