# Generated by Django 4.1.1 on 2022-10-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
