# Generated by Django 4.1.1 on 2022-10-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_userregister_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
