# Generated by Django 4.1.1 on 2022-10-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_userregister_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
