# Generated by Django 4.1.1 on 2022-10-07 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_userregister_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregister',
            options={},
        ),
        migrations.AlterModelManagers(
            name='userregister',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='username',
        ),
    ]
