# Generated by Django 4.1.1 on 2022-10-07 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_alter_userregister_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='last_login',
        ),
    ]
