# Generated by Django 4.1.1 on 2022-10-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_alter_userregister_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='status',
            field=models.CharField(blank=True, choices=[('S', 'Success'), ('F', 'Failed')], default='S', max_length=1, null=True),
        ),
    ]
