# Generated by Django 4.1.1 on 2022-10-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_userregister_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='status',
        ),
    ]
